#!/bin/bash

# Fetch ONNX models from latest GitHub Actions run
# This script downloads the ONNX models artifact generated by the CI pipeline
#
# Usage:
#   ./scripts/fetch_onnx_models.sh [repo] [output_dir]
#
# Environment variables:
#   GITHUB_TOKEN - GitHub API token (optional, for private repos or higher rate limits)
#   WORKFLOW_NAME - Name of the workflow to use (default: "ONNX Models Release")

set -e

REPO="${1:-supastishn/PojavBounce}"
OUTPUT_DIR="${2:-.}"
WORKFLOW_NAME="${WORKFLOW_NAME:-ONNX Models Release}"
GITHUB_TOKEN="${GITHUB_TOKEN:-}"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Build curl headers
build_headers() {
    local headers=(-H "Accept: application/vnd.github.v3+json")
    if [ -n "$GITHUB_TOKEN" ]; then
        headers+=(-H "Authorization: token $GITHUB_TOKEN")
    fi
    echo "${headers[@]}"
}

log_info "Fetching ONNX models from latest GitHub Actions run"
log_info "Repository: $REPO"
log_info "Workflow: $WORKFLOW_NAME"

# Get workflow ID
log_info "Looking up workflow '$WORKFLOW_NAME'..."
HEADERS=$(build_headers)
WORKFLOW=$(curl -s ${HEADERS[@]} \
    "https://api.github.com/repos/$REPO/actions/workflows" \
    | grep -o '"id": [0-9]*' | head -1 | cut -d' ' -f2)

if [ -z "$WORKFLOW" ]; then
    log_error "Could not find workflow '$WORKFLOW_NAME'"
    exit 1
fi

log_info "Found workflow ID: $WORKFLOW"

# Get latest successful run
log_info "Fetching latest successful run..."
RUN=$(curl -s ${HEADERS[@]} \
    "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW/runs?status=success&per_page=1" \
    | grep -o '"id": [0-9]*' | head -1 | cut -d' ' -f2)

if [ -z "$RUN" ]; then
    log_error "No successful runs found for workflow"
    exit 1
fi

log_info "Found run ID: $RUN"

# Get artifacts for this run
log_info "Fetching artifacts from run..."
ARTIFACTS=$(curl -s ${HEADERS[@]} \
    "https://api.github.com/repos/$REPO/actions/runs/$RUN/artifacts")

# Find ONNX models artifact (looks for onnx-models-opset9-*)
ARTIFACT_ID=$(echo "$ARTIFACTS" | grep -o '"id": [0-9]*' | grep -o '[0-9]*' | head -1)
ARTIFACT_NAME=$(echo "$ARTIFACTS" | grep -o '"name": "onnx-models-opset9-[^"]*' | cut -d'"' -f4)

if [ -z "$ARTIFACT_ID" ]; then
    log_warn "No onnx-models-opset9 artifacts found in latest run"
    log_info "Artifacts in this run:"
    echo "$ARTIFACTS" | grep -o '"name": "[^"]*' | cut -d'"' -f4 || true
    exit 1
fi

log_info "Found artifact: $ARTIFACT_NAME"

# Download artifact
log_info "Downloading artifact..."
mkdir -p "$OUTPUT_DIR"
DOWNLOAD_URL="https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT_ID/zip"

if [ -n "$GITHUB_TOKEN" ]; then
    curl -L \
        -H "Authorization: token $GITHUB_TOKEN" \
        -o "$OUTPUT_DIR/onnx-models-artifact.zip" \
        "$DOWNLOAD_URL"
else
    curl -L \
        -o "$OUTPUT_DIR/onnx-models-artifact.zip" \
        "$DOWNLOAD_URL"
fi

log_info "Extracting artifact..."
cd "$OUTPUT_DIR"
unzip -q onnx-models-artifact.zip

# The artifact contains onnx-models.zip, extract it
if [ -f "onnx-models.zip" ]; then
    log_info "Extracting ONNX models..."
    unzip -q onnx-models.zip
    rm onnx-models.zip
    rm onnx-models-artifact.zip
    log_info "Done! ONNX models extracted to: $OUTPUT_DIR/models/"

    # Show model info
    log_info "Generated models:"
    python3 << 'EOF' 2>/dev/null || find models -name "*.onnx" -exec ls -lh {} \; || true
import onnx
from pathlib import Path

models_dir = Path("models")
if models_dir.exists():
    for model_file in sorted(models_dir.glob("*.onnx")):
        try:
            model = onnx.load(str(model_file))
            ir_version = model.ir_version
            opset = model.opset_import[0].version if model.opset_import else "unknown"
            size_mb = model_file.stat().st_size / (1024 * 1024)
            print(f"  {model_file.name}: IR v{ir_version}, opset {opset}, {size_mb:.2f} MB")
        except Exception as e:
            print(f"  {model_file.name}: Error - {e}")
EOF
else
    log_error "onnx-models.zip not found in artifact"
    exit 1
fi
